export class PAGE_PATH {
  static readonly MAIN_PAGE: string = "main_page"
  static readonly MAIN_PAGE_ID: string = "mainNavigation"
  static readonly SEARCH_PAGE: string = "SearchView"
  static readonly LOGIN_PAGE: string = "LoginView"
  static readonly SCHOOL_PICKER_PAGE: string = "SchoolPickerView"
  static readonly TASK_DETAIL_PAGE: string = "TaskDetailView"
  static readonly SQUARE_DETAIL_PAGE: string = "SquareDetailView"
  static readonly CHAT_PAGE: string = "ChatView"
  static readonly NOTIFICATIONS_PAGE: string = "NotificationsView"
  static readonly REPUTATION_PAGE: string = "ReputationView"
  static readonly MALL_PAGE: string = "MallView"
  static readonly EDIT_PROFILE_PAGE: string = "EditProfileView"
}
